(lang dune 3.16)

(name aslp_server)

(generate_opam_files true)

(source
 (github  UQ-PAC/aslp))

(authors "ailrst")
(maintainers "ailrst")

(license BSD-3-Clause)

(documentation https://github.com/UQ-PAC/aslp)

(package
 (name aslp_server)
 (synopsis "REST server for ASLp")
 (description "")
 (depends ocaml dune
    "cohttp-lwt-unix"
    "yojson"
    "asli"
 )
 )

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
